### ISSUE TITLE
Mode Buttons (Graphic) are reversed

### ISSUE THREAD

**Issue by jminutaglio** [DDraiman1990/DroidTimeSelection#15]
The mode buttons seem to be reversed:
- in clock mode, the clock button shows (should be the keyboard)
- in picker mode, the keyboard shows (should be the clock)

Re:
<img width="344" alt="Screen Shot 2021-03-28 at 11 59 17 PM" src="https://user-images.githubusercontent.com/49879291/112786380-204be800-9024-11eb-937e-00bba6be41e5.png">

<img width="344" alt="Screen Shot 2021-03-29 at 12 16 26 AM" src="https://user-images.githubusercontent.com/49879291/112786386-23df6f00-9024-11eb-82da-868f9dcd1f2d.png">

**Comment by DDraiman1990** [comment]
An easy fix. Will address this tonight.

**Comment by DDraiman1990** [comment]
Updated with version 2.0.1 which is now live. Thanks for bringing this up.
